name: Manual release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version to create'
        default: 'v'
        required: true
      commit:
        description: 'Branch'
        default: 'main'
        required: true

jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build package
        run: ./mvnw install
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/kafka-consumer"
          tag: ${{ github.event.inputs.tag }}
          commit: ${{ github.event.inputs.commit }}
          token: ${{ secrets.GITHUB_TOKEN }}
